################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"

enableGitInfo = true
languageCode = "en-us"

# site title
title = "Puzzle Ansible Techlabs"

# theme
theme = "dot"

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

[frontmatter]
publishDate = ["publishDate", "date", ":git"]

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/puzzle_classic_rgb.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/puzzle_classic_bg_rgb.png"
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Roboto"

# public Git Repo - used for "improve this page" links
gitRepoUrl = "https://github.com/puzzle/ansible-techlab"

############################## social links ##############################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/puzzle/ansible-techlab"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/puzzleitc"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://linkedin.com/company/puzzle-itc"

################################# language ################################
[Languages]

  ################################ English Language ######################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  weight = 1
  home = "Home"
  copyright = "Ansible Techlabs are copyright &copy; [Puzzle ITC](https://puzzle.ch) 2020."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Puzzle Website"
        url = "https://www.puzzle.ch"


    # banner
    [Languages.en.params.banner]
      title = "Puzzle Ansible Techlabs"
      description = "Learning Ansible from the ground up"
      bg_image = "images/pic_puzzle_man.png"
      placeholder = "Just enter terms to query our labs content"

    # Topics
    [Languages.en.params.topics]
      title = "Techlab Sections"